//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaigMedicalStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DistributorManufacturer
    {
        public int DistributorManufacturerId { get; set; }
        public int DistributorId { get; set; }
        public int ManufacturerId { get; set; }
    
        public virtual Distributor Distributor { get; set; }
        public virtual Manufacturer Manufacturer { get; set; }
    }
}
